
server:
  port: 8083
spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/eInventory
    username: root
    password: Anuradha@01

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

