#server:
#  port: 8083
#  cache:
#    type: redis
#    redis:
#      host: localhost
#      port: 6379
#      cache:
#        time-to-live: 60000
#        eviction-policy: lru
#
#eureka:
#  client:
#    register-with-eureka : true
#    fetch-registry : true
#    service-url :
#      defaultZone : http://localhost:8761/eureka/
#  instance :
#    hostname : localhost
#
#
#
#logging:
#  file:
#    name: C:/Users/sparrow/Downloads/Logs/loggers.log


server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eInventory
    username: root
    password: Anuradha@01

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

logging:
  file:
    name: C:/Users/sparrow/Downloads/Logs/loggers.log

management:
  tracing:
    sampling:
      probability: 1.0
