server:
  port: 8989

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5000


#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/v1/user/**,/api/address/**
#          filters:
#            - name: AuthenticationFilter
#
#        - id: cart-service
#          uri: lb://CART-SERVICE
#          predicates:
#            - Path=/api/cart/**
#          filters:
#            - name: AuthenticationFilter
#
#        - id: inventory-service
#          uri: lb://INVENTORY-SERVICE
#          predicates:
#            - Path=/api/inventory/**,/api/products/**
#          filters:
#            - name: AuthenticationFilter
#
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/order/**
#          filters:
#            - name: AuthenticationFilter
#
#        - id: notification-service
#          uri: lb://NOTIFICATION-SERVICE
#          predicates:
#            - Path=/api/order/**
#          filters:
#            - name: AuthenticationFilter
#
#        - id: security-service
#          uri: lb://SECURITY-SERVICE
#          predicates:
#            - Path=/api/security/**
#          filters:
#            - name: AuthenticationFilter
#
#        - id: wishlist-service
#          uri: lb://WISHLIST-SERVICE
#          predicates:
#            - Path=/api/wishlist/**
#          filters:
#            - name: AuthenticationFilter



resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50 # Trigger circuit breaker if 50% of calls fail
        wait-duration-in-open-state: 30s # Wait for 30 seconds before attempting a call again
        slow-call-rate-threshold: 100 # Set the threshold for slow calls, 100 means all slow calls trigger breaker
        slow-call-duration-threshold: 2s # Calls that take longer than 2 seconds are considered slow
        permitted-number-of-calls-in-half-open-state: 3 # Number of permitted calls when half open
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10 # Use the last 10 calls to calculate failure rate
        minimum-number-of-calls: 5 # Minimum number of calls before circuit breaker is evaluated
        automatic-transition-from-open-to-half-open-enabled: true # Auto transition to half-open

      cartServiceCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true

      inventoryServiceCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true

      orderServiceCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
