spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: company-microservice
          uri: http://localhost:8082
          predicates:
            - Path=/company/**
        - id: review-microservice
          uri: http://localhost:8083
          predicates:
            - Path=/review/**
        - id: job-microservice
          uri: http://localhost:8081
          predicates:
            - Path=/job/**

server:
  port: 8989


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

