server:
  port: 8081

eureka:
  client:
    register-with-eureka : true
    fetch-registry : true
    service-url :
      defaultZone : http://localhost:8761/eureka/
  instance :
    hostname : localhost


spring:
<<<<<<< HEAD
  zipkin:
    base-url: http://localhost:9411

logging:
  file:
    name: C:/Users/sparrow/Downloads/Logs/loggers.log


=======
  application:
    name: USER-SERVICE
  cloud:
    config:
      uri: http://localhost:9196
  config:
    import: configserver:http://localhost:9196
>>>>>>> b253af3 (Cloud config & EDA)

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      userService:
        maxRetryAttempts: 5
        waitDuration: 10s