
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: order-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8087

spring:
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      uri: http://localhost:9196
  config:
    import: configserver:http://localhost:9196
  datasource:
    url: jdbc:mysql://localhost:3306/eOrder
    username: root
    password: Anuradha@01
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*' # Allow all packages for deserialization
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer