server:
  port: 8084

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: WISHLIST-SERVICE
  cloud:
    config:
      uri: http://localhost:9196
  config:
    import: configserver:http://localhost:9196
