server:
  port: 8082

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: CART-SERVICE
  cloud:
    config:
      uri: http://localhost:9196
  config:
    import: configserver:http://localhost:9196

