server:
  port: 8082

eureka:
  client:
    register-with-eureka : true
    fetch-registry : true
    service-url :
      defaultZone : http://localhost:8761/eureka
  instance :
    prefer-ip-address: true
    hostname : localhost


spring:
  application:
    name: CART-SERVICE
  zipkin:
    base-url: http://localhost:9411

logging:
  file:
    name: C:/Users/sparrow/Downloads/Logs/loggers.log
